config/routes.rb
Twitter::Application.routes.draw do
  get "stat/index"

  resources :tweets

  resources :zombies

  get "home/index"

   root :to => 'home#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie
  
  validates :zombie_id, :presence => true
  validates :tweet, :presence => true, :length =>{:maximum=>155, :minimum=>2}
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  has_many :tweets
  
  validates :username, :presence => true, :length => {:minimum=>2, :maximum=>20}, :uniqueness =>true
  validates :password, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @t = Tweet.last
    @z = @t.zombie
    @title = "Home"
  end

end

app/controllers/stat_controller.rb
class StatController < ApplicationController
  def index
    @zombie_last = Zombie.last.username
    @zombie_count = Zombie.count
    @tweet_count = Tweet.count
    @tweet_last = Tweet.last.tweet
    @title = "Stats"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @title = "#{Tweet.count} Tweets"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
    @zombie = @tweet.zombie
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new
    @zombie = Zombie.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(params[:tweet])

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, :notice => 'Tweet was successfully created.' }
        format.json { render :json => @tweet, :status => :created, :location => @tweet }
      else
        format.html { render :action => "new" }
        format.json { render :json => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, :notice => 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

 
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all(:order => 'created_at DESC')
    @title = "#{Zombie.count} Zombies"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])
    /@tweet = Tweet.where(:zombie_id=>@zombie.id).order('created_at DESC')/
    @tweet = @zombie.tweets
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, :notice => 'Zombie was successfully created.' }
        format.json { render :json => @zombie, :status => :created, :location => @zombie }
      else
        format.html { render :action => "new" }
        format.json { render :json => @zombie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, :notice => 'Zombie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @zombie.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Twitter"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stat_helper.rb
module StatHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/home/index.html.erb
<div class='box left m-color' style="width:300px;text-shadow: -1px -1px 1px rgba(0,0,0,0.8),1px 1px 1px white; ">
	<span class='b center'style='font-size:30px;'>Last Tweet</span><br /><span style="text-shadow:none;"><%=@t.tweet%> <br /><span class='right'>by <%= link_to @z.username, @z, :class=>"link_home"%></span></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=title%></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style='background:#3A7EEC;' class='<%=controller_name%>'>
	<div id="bartop">
	<%= link_to "List of Zombies", zombies_path, :class=>'m-color transition top_menu', :id =>'zombies'%> <span class='pipe'>|</span> 
	<%= link_to "List of Tweets", tweets_path, :class=>'m-color transition top_menu', :id =>'tweets' %> <span class='pipe'>|</span> 
	<%= link_to "Statistics", {:controller=>"stat"}, :class=>'m-color transition top_menu', :id =>'stat'%>
	 <%= link_to 'Sign in', new_zombie_path, :class=>"right"%>
	
	</div>
<%= yield %>
<div class='clear'></div>
<%if controller_name != 'home'%>
	<%= render 'tweets/test' %>
	<%end%>
</body>
</html>

app/views/stat/index.html.erb
<span class='b'>Last register:</span> <%= @zombie_last %><br />
<span class='b'>Total Accounts:</span> <%= @zombie_count %><br />
<span class='b'>Last Tweet: </span>
<% if(@tweet_count != 0) %>
<%= @tweet_last %><br />
<%else%>
<i>none</i><br />
<%end%>
<span class='b'>Total Tweet:</span> <%= @tweet_count %><br />
<%= render 'tweets/test'%>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet %><br />
    <%= f.text_area :tweet %>
  </div>
  <div class="field">
    <%= f.label :zombie_id %><br />
	<select name='tweet[zombie_id]' id="tweet_zombie_id">
	<%@zombie.each do |z|%>
	<option value=<%= z.id%>><%=z.username%></option>
	<%end%>
	</select>
<!--    <%= f.number_field :zombie_id %>-->
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/_test.html.erb
<br /><%= link_to "Homepage", root_path, :id => 'mono' %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Tweet</th>
    <th>Zombie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.tweet %></td>
    <td><%= Zombie.find(tweet.zombie_id).username %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %><br />

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tweet:</b>
  <%= @tweet.tweet %>
</p>

<p>
  <b>Zombie:</b>
  <%= @zombie.username %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Created</th>
    <th></th>
	 <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.username %></td>
    <td><%= zombie.password %></td>
	<td><%=l zombie.created_at %></td>
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Destroy', zombie, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @zombie.username %>
</p>

<p>
  <b>Password:</b>
  <%= @zombie.password %>
</p>
<b>List of tweets from this user</b><br />
<%@tweet.each do |t|%>
<div class='box'>
<i><%=l t.created_at%></i>
<br />
<%=t.tweet%> 
</div>
<%end%>
<%if (@tweet.size == 0)%>
None yet<br />
<%end%>
<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>